spring:
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    mode: HTML
  profiles:
    active: dev
  messages:
    basename: /messages
    encoding: UTF-8
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      
    database: mysql
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
      
server:
  tomcat:
    uri-encoding: UTF-8
  
banner:
  charset: UTF-8	
    

comment.avatar: /images/avatar.png