spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: Kai12348
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  

logging:
  level:
    root: info
    com.lrm: debug
  file: log/blog-dev.log



